const tabs=[['overview','⌂ Обзор'],['keys','🔑 API / Ключи'],['hori','♡ Хори'],['bot','◉ Бот'],['model','◈ Модель'],['lora','◇ LoRA'],['memory','☷ Память'],['files','▤ Файлы'],['render','▣ Render'],['colab','▤ Colab'],['github','◈ GitHub'],['logs','≋ Логи']];const tabIds=tabs.map(x=>x[0]);let tab=tabIds.includes(location.hash.slice(1))?location.hash.slice(1):'overview',s={renderServices:[],envKeys:[]};let logs=[];
const $=x=>document.getElementById(x);async function api(p,o={}){
 const ctrl=new AbortController();
 const timer=setTimeout(()=>ctrl.abort(),5000);
 try{
  const r=await fetch(p,{headers:{'Content-Type':'application/json'},...o,signal:ctrl.signal,cache:'no-store'});
  const text=await r.text();
  let d={}; try{d=text?JSON.parse(text):{}}catch{d={raw:text}}
  if(!r.ok)throw Error(d.error||'HTTP '+r.status);
  return d
 }catch(e){
  if(e.name==='AbortError') throw Error('Таймаут API (5 сек)');
  throw e
 }finally{clearTimeout(timer)}
}
function nav(){ $('nav').innerHTML=tabs.map(x=>'<button type="button" class="'+(x[0]===tab?'on':'')+'" data-tab="'+x[0]+'">'+x[1]+'</button>').join('');document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>{const next=b.dataset.tab;if(!tabIds.includes(next))return;tab=next;history.replaceState(null,'','#'+tab);render();window.scrollTo({top:0,behavior:'smooth'})}));}
function card(t,b){return '<section class="card"><h3>'+t+'</h3>'+b+'</section>'}
function saveBtn(label='💾 Сохранить изменения'){return '<div class="savebar"><button class="save" onclick="save()">'+label+'</button><span id="saved">Изменения не сохранены</span></div>'}function inp(k,label,extra=''){return '<label>'+label+'<input value="'+esc(s[k]??'')+'" oninput="s.'+k+'=this.value" '+extra+'></label>'}function esc(x){return String(x).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function render(){nav();$('title').textContent=tabs.find(x=>x[0]===tab)[1];let c='';
if(tab==='keys')c=card('API-ключи и секреты','<p class="muted">Полные значения доступны прямо из панели. Они не записываются в hori-control-config.json.</p><div class="actions"><button class="action" onclick="loadSecrets(true)">🔓 Показать полные ключи</button><button class="action" onclick="loadSecrets(false)">🔒 Скрыть</button></div><div id="secretsBox" class="term">Нажми «Показать полные ключи».</div>');
if(tab==='overview')c='<div id="dash"><div class="hero"><div class="ey">LIVE DASHBOARD</div><h2 style="margin:7px 0 5px">Hori Control Center</h2><div class="muted">Мониторинг Telegram, Render, модели, GitHub и памяти в одном месте.</div><div class="actions" style="margin-top:14px"><button class="action" onclick="loadDashboard()">🔄 Обновить всё</button><button class="action" onclick="tab=\'bot\';render()">◉ Управление ботом</button><button class="action" onclick="tab=\'model\';render()">◈ Менеджер моделей</button><span class="muted">🔓 Панель без входа</span></div></div><div class="grid g3" id="dashCards"><div class="card"><h3>Telegram</h3><div class="stat">…</div><div class="muted">проверка</div></div><div class="card"><h3>Model</h3><div class="stat">…</div><div class="muted">проверка</div></div><div class="card"><h3>Infrastructure</h3><div class="stat">…</div><div class="muted">Render / GitHub</div></div></div>'+card('Модель и fallback','<div class="flow"><b>Primary: '+esc(s.model)+'</b><b>Cloudflare: fallback</b><b>Pollinations: fallback</b><b>LoRA: '+esc(s.lora)+'</b></div>')+card('Live monitoring','<div id="liveState" class="term">Загрузка…</div>')+card('Последние события','<div id="dashLogs" class="term">Загрузка…</div>');if(tab==='hori')c=card('Личность Хори',inp('name','Имя')+'<label>System prompt<textarea rows="12" oninput="s.system=this.value">'+esc(s.system)+'</textarea></label><div class="grid g3">'+inp('temperature','Temperature','type="number" min="0" max="2" step=".05"')+inp('topP','Top P','type="number" min="0" max="1" step=".05"')+inp('maxTokens','Max tokens','type="number" min="1"')+'</div>'+saveBtn('💾 Сохранить параметры Хори'));
if(tab==='model')c=card('Основная модель',inp('model','Model ID')+inp('hfUrl','Inference / HF URL','placeholder="https://..."')+inp('hfModelUrl','Hugging Face model URL')+'<div class="actions"><button class="action" onclick="testHF()">🧪 Проверить модель</button><button class="action" onclick="testModel()">▶️ Тест генерации</button></div>'+saveBtn('💾 Сохранить модель'))+card('API / провайдеры','<div class="row"><span>Hugging Face</span><b>'+esc(s.hfUrl)+'</b></div><div class="row"><span>Render API</span><b>'+esc(s.renderApiBase)+'</b></div><div class="row"><span>GitHub API</span><b>'+esc(s.githubApiBase)+'</b></div><div class="row"><span>Cloudflare API</span><b>'+esc(s.cloudflareApiBase)+'</b></div><div class="row"><span>Pollinations</span><b>'+esc(s.pollinationsApiBase)+'</b></div><div class="row"><span>Telegram Bot API</span><b>'+esc(s.telegramApiBase)+'</b></div>')+card('Fallback','<div class="row"><span>Qwen / Hori</span><b>ACTIVE</b></div><div class="row"><span>Cloudflare</span><b>FALLBACK</b></div><div class="row"><span>Pollinations</span><b>FALLBACK</b></div>');if(tab==='lora')c=card('LoRA',inp('lora','Активная LoRA')+inp('loraWeight','Вес LoRA','type="number" min="0" max="2" step=".05"')+'<label>Источник<input id="loraSource" placeholder="username/repository"></label><div class="actions"><button class="action">🔄 Перезагрузить LoRA</button><button class="action">↩️ Подготовить откат</button></div>'+saveBtn('💾 Сохранить LoRA'));
if(tab==='render')c=card('Render — полный контроль',inp('renderUrl','Service URL','placeholder="https://...onrender.com"')+'<div class="actions"><button class="action" onclick="renderStatus()">🔎 API</button><button class="action" onclick="loadRenderDeploys()">🚀 Деплои</button><button class="action" onclick="loadRenderLogs()">📜 Логи</button><button class="action" onclick="loadRenderEnv()">🔐 Env</button><button class="action" onclick="renderDeploy()">⚡ Деплой</button><button class="action" onclick="openURL(s.renderUrl||&#39;https://dashboard.render.com&#39;)">↗ Render</button></div>'+saveBtn('💾 Сохранить Render'))+card('Сервисы Render','<div id="renderServicesBox" class="term">Нажми API.</div>')+card('Деплои','<div id="renderDeploysBox" class="term">Нажми «Деплои».</div>')+card('Логи','<div id="renderLogsBox" class="term">Нажми «Логи».</div>')+card('Environment','<p class="muted">Управление переменными окружения Render. Секреты не выводятся в интерфейс открытым текстом.</p><textarea id="renderEnvText" rows="16" placeholder="KEY=value"></textarea><div class="actions"><button class="action" onclick="loadRenderEnv()">📥 Загрузить</button><button class="action" onclick="saveRenderEnv()">💾 Применить</button></div>');
if(tab==='colab')c=card('Google Colab / обучение',inp('colabUrl','Notebook URL','placeholder="https://colab.research.google.com/..."')+'<div class="grid g3">'+inp('trainingBase','Base model')+inp('trainingEpochs','Epochs','type="number"')+inp('trainingBatch','Batch size','type="number"')+'</div><div class="actions"><button class="action" onclick="openURL(s.colabUrl)">↗ Открыть notebook</button></div>'+saveBtn('💾 Сохранить обучение')+'<p class="muted">Настройки обучения сохраняются в панели. Сам запуск Colab выполняется в Colab.</p>');
if(tab==='github')c=card('GitHub — полный контроль',inp('githubRepo','Репозиторий')+'<label>Ветка<input value="'+esc(s.githubBranch||'main')+'" oninput="s.githubBranch=this.value"></label><div class="actions"><button class="action" onclick="githubStatus()">🔎 API</button><button class="action" onclick="loadBranches()">🌿 Ветки</button><button class="action" onclick="loadWorkflows()">⚙️ Workflows</button><button class="action" onclick="loadRuns()">▶️ Runs</button><button class="action" onclick="openURL(&#39;https://github.com/&#39;+s.githubRepo)">↗ Репозиторий</button></div>'+saveBtn('💾 Сохранить GitHub'))+card('GitHub Actions','<div class="grid g2"><label>Workflow<input id="workflowName" placeholder="workflow.yml"></label><label>Ref<input id="workflowRef" value="'+esc(s.githubBranch||'main')+'"></label></div><div class="actions"><button class="action" onclick="dispatchWorkflow()">▶️ Запустить workflow</button><button class="action" onclick="loadWorkflows()">📋 Обновить</button></div><div id="workflowBox" class="term">Здесь появятся workflows.</div>')+card('Последние runs','<div id="runsBox" class="term">Нажми «Runs».</div>');
if(tab==='bot')c=card('Telegram / Bot',inp('botUrl','Bot / Bridge URL','placeholder="https://telegramxor.onrender.com"')+'<div class="actions"><button class="action" onclick="loadBotStatus()">🔄 Обновить статус</button><button class="action" onclick="pingBot()">🟢 Проверить бота</button><button class="action" onclick="renderDeploy()">🚀 Деплой бота</button></div>')+card('Управление ботом','<div class="grid g2"><label>Бот включён <select id="ctlEnabled"><option value="true">Да</option><option value="false">Нет</option></select></label><label>Пишет первым <select id="ctlProactive"><option value="true">Да</option><option value="false">Нет</option></select></label><label>Голос <select id="ctlVoice"><option value="true">Включён</option><option value="false">Выключен</option></select></label><label>Фото <select id="ctlPhoto"><option value="true">Включено</option><option value="false">Выключено</option></select></label><label>Автоматический режим <select id="ctlAuto"><option value="true">Да</option><option value="false">Нет</option></select></label><label>Режим модели <select id="ctlModel"><option value="auto">Auto / fallback</option><option value="local">Local</option><option value="pollinations">Pollinations</option></select></label></div><div class="actions"><button class="action" onclick="saveBotControl()">💾 Применить управление</button><button class="action" onclick="loadBotControl()">📥 Загрузить настройки</button></div>')+card('Тестовое сообщение','<div class="grid g2"><label>Chat ID<input id="testChat" placeholder="ID Telegram чата"></label><label>Текст<input id="testText" value="Проверка связи с Hori Control ✓"></label></div><button class="action" onclick="sendBotTest()">📨 Отправить тест</button>')+card('Состояние','<div id="botState" class="term">Нажми «Обновить статус».</div>')+saveBtn('💾 Сохранить URL бота');
if(tab==='memory')c=card('Память Хори','<p class="muted">Редактируй реальные JSON-файлы бота прямо из панели. Выбери файл и нажми «Загрузить».</p><label>Файл<select id="memFile"><option>hori_memory.json</option><option>hori_diary.json</option><option>hori_personality.json</option><option>hori_knowledge.json</option><option>hori_training.json</option></select></label><textarea id="memText" rows="20" placeholder="JSON"></textarea><div class="actions"><button class="action" onclick="loadMem()">📥 Загрузить</button><button class="action" onclick="saveMem()">💾 Записать в GitHub</button><button class="action" onclick="formatMem()">✨ Форматировать JSON</button></div>');
if(tab==='files')c=card('Файлы проекта','<p class="muted">Можно читать и изменять файлы репозитория через сервер панели. Токен остаётся на Render.</p><label>Путь<input id="filePath" value="server.ts" placeholder="server.ts"></label><textarea id="fileText" rows="22" placeholder="Содержимое файла"></textarea><div class="actions"><button class="action" onclick="loadFile()">📥 Открыть файл</button><button class="action" onclick="saveFile()">💾 Сохранить файл в GitHub</button></div>');
if(tab==='logs')c=card('Живые логи','<div class="actions"><button class="action" onclick="refreshLogs()">🔄 Обновить</button></div><br><div class="term">'+logs.map(x=>'['+new Date(x.time).toLocaleTimeString()+'] '+x.message).join('\\n')+'</div>');
$('content').innerHTML=c;setTimeout(()=>autoLoadTab(),50)}
async function autoLoadTab(){try{if(tab==='overview')return loadDashboard();if(tab==='render'){await Promise.allSettled([renderStatus(),loadRenderDeploys(),loadRenderLogs(),loadRenderEnv()]);return}if(tab==='github'){await Promise.allSettled([githubStatus(),loadBranches(),loadWorkflows(),loadRuns()]);return}if(tab==='bot')return loadBotStatus();if(tab==='logs')return refreshLogs();}catch(e){$('status').textContent='Автозагрузка: '+e.message}}
async function loadSecrets(reveal){try{const d=await api('/api/secrets?reveal='+(reveal?'1':'0'));$('secretsBox').textContent=d.secrets.map(x=>x.key+' = '+(x.configured?(reveal?x.value:'••••••••••'):'НЕ ЗАДАН')).join('\\n');$('status').textContent=reveal?'Ключи показаны':'Ключи скрыты'}catch(e){$('status').textContent='Secrets: '+e.message}}
async function load(){
 render();
 $('status').textContent='Проверяем API…';
 try{
  const cfg=await api('/api/config');
  s={...s,...cfg,renderServices:Array.isArray(cfg.renderServices)?cfg.renderServices:[],envKeys:Array.isArray(cfg.envKeys)?cfg.envKeys:[]};
  $('status').textContent='Сервер подключён ✓';
  render();
 }catch(e){
  $('status').textContent='API недоступен: '+e.message;
  console.error('Hori Control API:',e);
 }
 refreshLogs();
}
async function logout(){try{await api('/api/logout',{method:'POST'});location.reload()}catch{location.reload()}}
async function save(){try{await api('/api/config',{method:'PUT',body:JSON.stringify(s)});$('status').textContent='Сохранено ✓';if($('saved'))$('saved').textContent='Сохранено '+new Date().toLocaleTimeString();refreshLogs()}catch(e){$('status').textContent=e.message}}
async function refreshLogs(){try{logs=await api('/api/logs');if(tab==='logs')render()}catch{}}
async function loadDashboard(){
 try{
  const d=await api('/api/dashboard');
  const ok=v=>v&&v.ok?'ONLINE':'OFFLINE';
  const botName=d.bot?.data?.name||d.bot?.data?.service||'Telegram bot';
  $('dashCards').innerHTML='<div class="card"><h3>Telegram</h3><div class="stat '+(d.bot.ok?'green':'danger')+'">'+ok(d.bot)+'</div><div class="muted">'+esc(botName)+' · HTTP '+esc(d.bot.status||d.bot.data?.status||'—')+'</div></div><div class="card"><h3>Model</h3><div class="stat '+(d.model.ok?'green':'danger')+'">'+ok(d.model)+'</div><div class="muted">'+esc(s.model)+' · HF '+esc(d.model.status||'—')+'</div></div><div class="card"><h3>Infrastructure</h3><div class="stat '+(d.render.ok&&d.github.ok?'green':'danger')+'">'+(d.render.ok&&d.github.ok?'READY':'CHECK')+'</div><div class="muted">Render '+esc(d.render.status||'—')+' · GitHub '+esc(d.github.status||'—')+'</div></div>';
  $('liveState').textContent=JSON.stringify({time:d.time,bot:d.bot.data||d.bot.error,autonomy:d.autonomy.data||d.autonomy.error,providers:d.providers.data||d.providers.error},null,2);
  $('dashLogs').textContent=(d.logs||[]).map(x=>'['+new Date(x.time).toLocaleTimeString()+'] '+x.message).join('\\n')||'Нет событий';
  $('status').textContent='Dashboard обновлён ✓';
 }catch(e){$('status').textContent='Dashboard: '+e.message}
}
async function renderStatus(){try{let d=await api('/api/render/status');$('status').textContent='Render HTTP '+d.status;refreshLogs()}catch(e){$('status').textContent=e.message}}
async function githubStatus(){try{let d=await api('/api/github/repo');$('status').textContent='GitHub '+(d.data?.full_name||'OK');refreshLogs()}catch(e){$('status').textContent=e.message}}
async function testHF(){try{let d=await api('/api/hf/status');$('status').textContent='HF HTTP '+d.status;refreshLogs()}catch(e){$('status').textContent=e.message}}
async function testModel(){try{let d=await api('/api/model/test',{method:'POST',body:JSON.stringify({payload:{prompt:'Ответь одним коротким предложением: привет'}})});$('status').textContent='Model HTTP '+d.status;refreshLogs()}catch(e){$('status').textContent=e.message}}
async function loadBotControl(){try{const d=await api('/api/bot/control');for(const [id,key] of [['ctlEnabled','enabled'],['ctlProactive','proactiveEnabled'],['ctlVoice','voiceEnabled'],['ctlPhoto','photoEnabled'],['ctlAuto','autoFirst'],['ctlModel','modelMode']])if($(id))$(id).value=String(d[key]);$('status').textContent='Настройки бота загружены ✓'}catch(e){$('status').textContent='Control: '+e.message}}
async function saveBotControl(){try{const body={enabled:$('ctlEnabled').value==='true',proactiveEnabled:$('ctlProactive').value==='true',voiceEnabled:$('ctlVoice').value==='true',photoEnabled:$('ctlPhoto').value==='true',autoFirst:$('ctlAuto').value==='true',modelMode:$('ctlModel').value};const d=await api('/api/bot/control',{method:'POST',body:JSON.stringify(body)});$('status').textContent=d.ok?'Управление применено ✓':'Ошибка';loadBotStatus()}catch(e){$('status').textContent='Control: '+e.message}}
async function loadBotStatus(){try{const d=await api('/api/bot/status');$('botState').textContent=JSON.stringify({health:d.health,autonomy:d.autonomy,providers:d.providers},null,2);$('status').textContent='Бот синхронизирован ✓';loadBotControl()}catch(e){$('status').textContent='Bot status: '+e.message}}
async function sendBotTest(){try{const chatId=Number($('testChat').value);const text=$('testText').value.trim();if(!chatId||!text)throw Error('Укажи Chat ID и текст');await api('/api/bot/test-message',{method:'POST',body:JSON.stringify({chatId,text})});$('status').textContent='Тест отправлен ✓'}catch(e){$('status').textContent='Test: '+e.message}}
async function pingBot(){try{let d=await api('/api/telegram/ping');$('status').textContent='Бот HTTP '+d.status;refreshLogs()}catch(e){$('status').textContent='Бот: '+e.message}}
async function renderDeploy(){if(!confirm('Запустить новый деплой Render?'))return;try{let d=await api('/api/render/deploy',{method:'POST',body:'{}'});$('status').textContent='Деплой запущен ✓';refreshLogs()}catch(e){$('status').textContent='Deploy: '+e.message}}
async function loadMem(){try{let d=await api('/api/github/file?path='+encodeURIComponent($('memFile').value)+'&branch='+encodeURIComponent(s.githubBranch||'main'));$('memText').value=d.content||'';$('status').textContent='Файл загружен ✓'}catch(e){$('status').textContent=e.message}}
async function saveMem(){try{JSON.parse($('memText').value);let d=await api('/api/github/file',{method:'PUT',body:JSON.stringify({path:$('memFile').value,branch:s.githubBranch||'main',content:$('memText').value,message:'Hori Control: update '+$('memFile').value})});$('status').textContent=d.ok?'Память записана ✓':'Ошибка записи';refreshLogs()}catch(e){$('status').textContent='JSON/GitHub: '+e.message}}
function formatMem(){try{$('memText').value=JSON.stringify(JSON.parse($('memText').value),null,2);$('status').textContent='JSON отформатирован ✓'}catch(e){$('status').textContent='Неверный JSON'}}
async function loadFile(){try{let d=await api('/api/github/file?path='+encodeURIComponent($('filePath').value)+'&branch='+encodeURIComponent(s.githubBranch||'main'));$('fileText').value=d.content||'';$('status').textContent='Файл загружен ✓'}catch(e){$('status').textContent=e.message}}
async function saveFile(){try{let d=await api('/api/github/file',{method:'PUT',body:JSON.stringify({path:$('filePath').value,branch:s.githubBranch||'main',content:$('fileText').value,message:'Hori Control: edit '+$('filePath').value})});$('status').textContent=d.ok?'Файл сохранён ✓':'Ошибка записи';refreshLogs()}catch(e){$('status').textContent=e.message}}
async function loadRenderDeploys(){try{const d=await api('/api/render/deploys');$('renderDeploysBox').textContent=d.body||JSON.stringify(d,null,2);$('status').textContent='Render deploys ✓'}catch(e){$('status').textContent=e.message}}
async function loadRenderLogs(){try{const d=await api('/api/render/logs');$('renderLogsBox').textContent=d.body||JSON.stringify(d,null,2);$('status').textContent='Render logs ✓'}catch(e){$('status').textContent=e.message}}
async function loadRenderEnv(){try{const d=await api('/api/render/env');$('renderEnvText').value=String(d.body||'').replace(/"value":"[^"]*"/g,'"value":"••••••••"');$('status').textContent='Render env loaded ✓'}catch(e){$('status').textContent=e.message}}
async function saveRenderEnv(){try{const lines=$('renderEnvText').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const variables=lines.map(x=>{const i=x.indexOf('=');return i>0?{key:x.slice(0,i),value:x.slice(i+1)}:null}).filter(Boolean);const changed=variables.filter(x=>x.value && !/^•+$/.test(x.value));if(!changed.length){$('status').textContent='Нет новых значений Env — ничего не изменено';return}await api('/api/render/env',{method:'PUT',body:JSON.stringify({variables:changed})});$('status').textContent='Render env применён ✓';loadRenderEnv()}catch(e){$('status').textContent='Render env: '+e.message}}
async function loadBranches(){try{const d=await api('/api/github/branches');const names=(d.data||[]).map(x=>x.name);if($('workflowRef'))$('workflowRef').value=s.githubBranch||names[0]||'main';if($('workflowBox'))$('workflowBox').textContent='Ветки:\n'+(names.join('\n')||'Нет веток');$('status').textContent='Branches ✓'}catch(e){$('status').textContent='Branches: '+e.message}}
async function loadWorkflows(){try{const d=await api('/api/github/workflows');$('workflowBox').textContent=JSON.stringify(d.data||d,null,2);$('status').textContent='Workflows ✓'}catch(e){$('status').textContent=e.message}}
async function loadRuns(){try{const d=await api('/api/github/runs');$('runsBox').textContent=JSON.stringify(d.data?.workflow_runs||d.data||d,null,2);$('status').textContent='Runs ✓'}catch(e){$('status').textContent=e.message}}
async function dispatchWorkflow(){try{const workflow=$('workflowName').value.trim();if(!workflow)throw Error('Укажи workflow');await api('/api/github/workflow',{method:'POST',body:JSON.stringify({workflow,ref:$('workflowRef').value.trim()||s.githubBranch||'main'})});$('status').textContent='Workflow запущен ✓';loadRuns()}catch(e){$('status').textContent=e.message}}
function openURL(x){if(x)window.open(x,'_blank')}
window.addEventListener('error',e=>{console.error('Hori Control JS error:',e.message);const el=$('status');if(el)el.textContent='Ошибка JS: '+e.message});
window.addEventListener('unhandledrejection',e=>{console.error('Hori Control promise error:',e.reason);const el=$('status');if(el)el.textContent='Ошибка: '+(e.reason?.message||e.reason)});
console.log('Hori Control frontend boot',new Date().toISOString());
load();setInterval(refreshLogs,10000);setInterval(()=>{if(tab==='overview')loadDashboard();else if(tab==='bot')loadBotStatus()},7000);